// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.asp.net.backend.TriviaData;

#nullable disable

namespace app.asp.net.backend.Migrations
{
    [DbContext(typeof(TriviaDBContext))]
    partial class TriviaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("app.asp.net.backend.TriviaModels.TCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TCategories");
                });

            modelBuilder.Entity("app.asp.net.backend.TriviaModels.TQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QCatId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("QCorrectOption")
                        .HasColumnType("TEXT");

                    b.Property<string>("QOptionA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QOptionB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QOptionC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QOptionD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QCatId");

                    b.ToTable("TQuestions");
                });

            modelBuilder.Entity("app.asp.net.backend.TriviaModels.TScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SCatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SPlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("STotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SCatId");

                    b.ToTable("TScores");
                });

            modelBuilder.Entity("app.asp.net.backend.TriviaModels.TQuestion", b =>
                {
                    b.HasOne("app.asp.net.backend.TriviaModels.TCategory", "QCategory")
                        .WithMany()
                        .HasForeignKey("QCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QCategory");
                });

            modelBuilder.Entity("app.asp.net.backend.TriviaModels.TScore", b =>
                {
                    b.HasOne("app.asp.net.backend.TriviaModels.TCategory", "SCategory")
                        .WithMany()
                        .HasForeignKey("SCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
